const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const fmt=(n,d=2)=>Number(n||0).toLocaleString('pt-BR',{minimumFractionDigits:d,maximumFractionDigits:d});
const money=n=>(Number(n||0)>=0?'+':'')+fmt(n);
const monthLabel=m=>{const [y,mo]=String(m).split('-');return new Date(Number(y),Number(mo)-1,1).toLocaleDateString('pt-BR',{month:'short'}).replace('.','')};
function set(id,v){const e=document.getElementById(id);if(e)e.textContent=v}
let dashboardData=null,metricData=null,filterData=null;
const APP_VERSION='V53';
let recentPage=1;
let recentPageSize=20;
let editingFilterId=null;

function renderCurve(c){
 const svg=$('#curve'); if(!svg)return;
 if(!c?.length){svg.innerHTML='<text x="50%" y="50%" text-anchor="middle" fill="#73849a">Sem dados para exibir</text>';return;}
 const w=700,h=260,p=28,vals=c.map(x=>Number(x.acumulado||0));
 const rawMin=Math.min(0,...vals),rawMax=Math.max(0,...vals);
 const range=Math.max(rawMax-rawMin,1),pad=range*0.08;
 const min=rawMin<0?rawMin-pad:0, max=rawMax>0?rawMax+pad:0, scale=Math.max(max-min,1);
 const xAt=i=>p+(w-2*p)*i/Math.max(1,c.length-1), yAt=v=>h-p-(v-min)/scale*(h-2*p), zero=yAt(0);
 const pts=c.map((x,i)=>[xAt(i),yAt(Number(x.acumulado||0))]);
 const labels=[min,max].filter((v,i,a)=>a.indexOf(v)===i).map(v=>`<text x="4" y="${yAt(v)+3}" class="axisLabel">${esc(fmt(v,0))}</text>`).join('');
 let segments='';
 for(let i=1;i<pts.length;i++){
   const a=pts[i-1],b=pts[i], va=vals[i-1],vb=vals[i], positive=vb>=0&&va>=0, negative=vb<0&&va<0;
   let color=positive?'#55e68a':negative?'#ff6870':'#b8c4d3';
   segments+=`<line x1="${a[0]}" y1="${a[1]}" x2="${b[0]}" y2="${b[1]}" stroke="${color}" stroke-width="3" stroke-linecap="round"/>`;
 }
 svg.innerHTML=`<line class="zeroLine" x1="${p}" y1="${zero}" x2="${w-p}" y2="${zero}"/><text x="${w-p+5}" y="${zero+3}" class="zeroLabel">0</text>${labels}${segments}`;
}
function renderBlocks(blocks){
 const tabs=$('#blockTabs'),body=$('#blockBody');
 if(!tabs||!body)return;
 const bs=blocks||[];
 tabs.innerHTML=bs.length?bs.map(b=>`<button class="blockTab" data-block="${b.bloco}"><b>Bloco ${b.bloco}</b><small>${b.inicio}-${b.fim} • ${b.entries} jogos</small></button>`).join(''):'<span class="muted">Nenhum bloco disponível.</span>';
 body.innerHTML=bs.map(b=>`<tr><td>Bloco ${b.bloco}</td><td>${b.entries}</td><td class="positive">${b.greens}</td><td class="negative">${b.reds}</td><td>${fmt(b.winrate,1)}%</td><td>${fmt(b.oddMedia,2)}</td><td class="${b.lucro>=0?'positive':'negative'}">${money(b.lucro)}</td><td class="${b.roi>=0?'positive':'negative'}">${fmt(b.roi,1)}%</td></tr>`).join('')||emptyRow(8,'Nenhum jogo passou pelo recorte.');
 tabs.querySelectorAll('.blockTab').forEach(btn=>btn.addEventListener('click',()=>{tabs.querySelectorAll('.blockTab').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const n=Number(btn.dataset.block);const row=bs.find(x=>x.bloco===n);if(row)body.innerHTML=`<tr><td>Bloco ${row.bloco}</td><td>${row.entries}</td><td class="positive">${row.greens}</td><td class="negative">${row.reds}</td><td>${fmt(row.winrate,1)}%</td><td>${fmt(row.oddMedia,2)}</td><td class="${row.lucro>=0?'positive':'negative'}">${money(row.lucro)}</td><td class="${row.roi>=0?'positive':'negative'}">${fmt(row.roi,1)}%</td></tr>`;}));
 if(bs[0])tabs.querySelector('.blockTab')?.classList.add('active');
}
function renderRecent(rows){
 const body=$('#recentBody'),pag=$('#recentPagination'),summary=$('#recentSummary'); if(!body||!pag)return;
 const all=Array.isArray(rows)?rows:[], total=all.length, pages=Math.max(1,Math.ceil(total/recentPageSize)); recentPage=Math.min(Math.max(1,recentPage),pages);
 const slice=all.slice().reverse().slice((recentPage-1)*recentPageSize,recentPage*recentPageSize);
 body.innerHTML=slice.map((x,i)=>`<tr><td>${(recentPage-1)*recentPageSize+i+1}</td><td>${esc(x.DATA)}</td><td>${esc(x.CONFRONTO)}</td><td>${esc(x.CAMPEONATO)}</td><td>${esc(x.mercado_label)}</td><td>${fmt(x.odd)}</td><td><b class="pill ${x.green?'green':'red'}">${x.green?'Green':'Red'}</b></td><td class="${x.pnl>=0?'positive':'negative'}">${money(x.pnl)}</td></tr>`).join('')||emptyRow(8,'Nenhuma entrada encontrada.');
 if(summary)summary.textContent=`${total.toLocaleString('pt-BR')} entradas • ${recentPageSize} por página`;
 const btns=[];btns.push(`<button class="secondary pageBtn" data-page="${Math.max(1,recentPage-1)}" ${recentPage<=1?'disabled':''}>‹</button>`);
 const windowPages=[];for(let i=1;i<=pages;i++){if(i<=3||i===pages||Math.abs(i-recentPage)<=1)windowPages.push(i);else if(windowPages.at(-1)!=='…')windowPages.push('…');}
 windowPages.forEach(i=>btns.push(i==='…'?'<span class="pageEllipsis">…</span>':`<button class="secondary pageBtn${i===recentPage?' active':''}" data-page="${i}">${i}</button>`));
 btns.push(`<button class="secondary pageBtn" data-page="${Math.min(pages,recentPage+1)}" ${recentPage>=pages?'disabled':''}>›</button>`);pag.innerHTML=btns.join('');pag.querySelectorAll('.pageBtn').forEach(b=>b.addEventListener('click',()=>{recentPage=Number(b.dataset.page);renderRecent(dashboardData?.rows||[]);}));
}
function renderDashboard(d){
 dashboardData=d;set('entries',Number(d.entries||0).toLocaleString('pt-BR'));set('winrate',fmt(d.winrate,1)+'%');set('avgodd',fmt(d.oddMedia,2));set('profit',money(d.lucro));set('roi',fmt(d.roi,1)+'%');set('dd','-'+fmt(Math.abs(d.drawdown)));set('fairOdd',d.fairOddMedia==null?'0,00':fmt(d.fairOddMedia,2));set('fairProfit',money(d.lucroJustoLiquido||0));set('fairROI',fmt(d.roiJustoLiquido||0,1)+'%');$('#profit')?.classList.toggle('negative',d.lucro<0);$('#profit')?.classList.toggle('positive',d.lucro>=0);renderCurve(d.curve||[]);
 const mb=$('#monthlyBars'),ml=$('#monthlyLabels');if(mb&&ml){mb.innerHTML='';ml.innerHTML='';const mx=Math.max(1,...(d.monthly||[]).map(x=>Math.abs(x.lucro)));(d.monthly||[]).forEach(x=>{const b=document.createElement('span');b.style.height=Math.max(6,Math.abs(x.lucro)/mx*100)+'%';if(x.lucro<0)b.classList.add('red');b.title=`${x.mes}: ${money(x.lucro)}`;mb.appendChild(b);const l=document.createElement('small');l.textContent=monthLabel(x.mes);ml.appendChild(l)})}
 const champs=d.championships||[];if($('#champBody'))$('#champBody').innerHTML=champs.map(champRow).join('')||emptyRow(5,'Nenhum campeonato no recorte.');const total=d.entries||1;if($('#donut'))$('#donut').style.setProperty('--green',((d.distributions?.green||0)/total*100)+'%');set('distTotal',Number(d.entries||0).toLocaleString('pt-BR'));set('greenCount','Green '+(d.distributions?.green||0));set('redCount','Red '+(d.distributions?.red||0));
 renderBlocks(d.blocks||[]);recentPage=1;renderRecent(d.rows||[]);
 if($('#champReportBody'))$('#champReportBody').innerHTML=champs.map(x=>`<tr><td>${esc(x.nome)}</td><td>${x.entries}</td><td class="positive">${x.greens}</td><td class="negative">${x.reds}</td><td>${fmt(x.winrate,1)}%</td><td>${fmt(x.oddMedia,2)}</td><td class="${x.lucro>=0?'positive':'negative'}">${money(x.lucro)}</td><td class="${x.roi>=0?'positive':'negative'}">${fmt(x.roi,1)}%</td></tr>`).join('')||emptyRow(8,'Nenhum campeonato encontrado.');
 const mm=$('#marketListBottom');if(mm){const selected=String(d.market||'');mm.innerHTML=`<div class="marketSummaryHead"><span>Mercado</span><span>Entradas</span><span>Winrate</span><span>P/L (${d.pnlRef==='JUSTA'?'Justa':'365'})</span><span>ROI</span><span>Odd justa</span><span>P/L justo</span><span>ROI justo</span></div>`+(d.markets||[]).map(x=>{const active=String(x.mercado)===selected;return `<div class="marketSummaryRow${active?' selected':''}"><b>${esc(x.label)}</b><span>${x.entries}</span><span>${fmt(x.winrate,1)}%</span><span class="${x.lucro>=0?'positive':'negative'}">${money(x.lucro)}</span><span class="${x.roi>=0?'positive':'negative'}">${fmt(x.roi,1)}%</span><span>${x.oddJustaMedia==null?'—':fmt(x.oddJustaMedia,2)}</span><span class="${(x.lucroJustoLiquido||0)>=0?'positive':'negative'}">${x.lucroJustoLiquido==null?'—':money(x.lucroJustoLiquido)}</span><span class="${(x.roiJustoLiquido||0)>=0?'positive':'negative'}">${x.roiJustoLiquido==null?'—':fmt(x.roiJustoLiquido,1)+'%'}</span></div>`}).join('')||'<span class="muted">Nenhum mercado disponível.</span>'}
}
function champRow(x){return `<tr><td>${esc(x.nome)}</td><td>${x.entries}</td><td>${fmt(x.winrate,1)}%</td><td class="${x.lucro>=0?'positive':'negative'}">${money(x.lucro)}</td><td>${fmt(x.roi,1)}%</td></tr>`}
function emptyRow(cols,msg){return `<tr><td colspan="${cols}" class="muted">${esc(msg)}</td></tr>`}
async function api(path,opts={}){const r=await fetch(path,{cache:'no-store',...opts});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||d.detail||JSON.stringify(d));return d}
function champPickerValues(id){const box=$(id);if(!box)return[];const all=box.querySelector('input[data-all="1"]');if(all?.checked)return[];return [...box.querySelectorAll('input[data-champ="1"]:checked')].map(x=>x.value).filter(Boolean)}
function setChampPicker(id,values=[],disabled=false){const box=$(id);if(!box)return;const vals=new Set((values||[]).map(String));const all=box.querySelector('input[data-all="1"]');const items=[...box.querySelectorAll('input[data-champ="1"]')];const has=vals.size>0;items.forEach(x=>{x.checked=has&&vals.has(String(x.value));x.disabled=disabled});if(all){all.checked=!has;all.disabled=disabled}box.classList.toggle('disabled',disabled);updateChampPickerSummary(id)}
function renderChampPicker(id,vals,selected=[],disabled=false){const box=$(id);if(!box)return;box.innerHTML=`<button type="button" class="pickerTrigger"><span class="pickerSummary">Todos os campeonatos</span><span class="pickerChevron">▾</span></button><div class="pickerMenu"><label class="pickerAll"><input type="checkbox" data-all="1"> <b>Todos</b></label><div class="pickerItems">${(vals||[]).map(v=>`<label><input type="checkbox" data-champ="1" value="${esc(v)}"> <span>${esc(v)}</span></label>`).join('')}</div></div>`;const trigger=box.querySelector('.pickerTrigger');const menu=box.querySelector('.pickerMenu');trigger?.addEventListener('click',e=>{e.preventDefault();if(trigger.disabled)return;document.querySelectorAll('.champPicker .pickerMenu.open').forEach(m=>{if(m!==menu)m.classList.remove('open')});menu?.classList.toggle('open')});const all=box.querySelector('input[data-all="1"]');all?.addEventListener('change',()=>{if(all.checked)box.querySelectorAll('input[data-champ="1"]').forEach(x=>x.checked=false);updateChampPickerSummary(id)});box.querySelectorAll('input[data-champ="1"]').forEach(x=>x.addEventListener('change',()=>{if(x.checked&&all)all.checked=false;const any=box.querySelector('input[data-champ="1"]:checked');if(!any&&all)all.checked=true;updateChampPickerSummary(id)}));setChampPicker(id,selected,disabled)}
document.addEventListener('click',e=>{if(!e.target.closest('.champPicker'))document.querySelectorAll('.champPicker .pickerMenu.open').forEach(m=>m.classList.remove('open'))});
function updateChampPickerSummary(id){const box=$(id);if(!box)return;const disabled=box.classList.contains('disabled');const all=box.querySelector('input[data-all="1"]');const vals=[...box.querySelectorAll('input[data-champ="1"]:checked')];const label=box.querySelector('.pickerSummary');if(label)label.textContent=disabled?(vals.length?`${vals.length} campeonato(s) definidos pelo filtro`:'Todos os campeonatos definidos pelo filtro'):(all?.checked||!vals.length?'Todos os campeonatos':`${vals.length} campeonato(s) selecionado(s)`);const trigger=box.querySelector('.pickerTrigger');if(trigger)trigger.disabled=disabled;const menu=box.querySelector('.pickerMenu');if(disabled)menu?.classList.remove('open')}
async function dash(){
 const btn=$('#apply');
 const market=$('#market')?.value||'OVER_2_5';
 const pnlRef=$('#pnlRef')?.value||'365';
 const filterName=$('#dashFilter')?.selectedOptions?.[0]?.textContent||'Sem filtro';
 if(btn){btn.disabled=true;btn.classList.add('loading');btn.innerHTML='<span class="spinner"></span> Aplicando...';}
 set('sideStatus','Atualizando...');
 set('configStatus',`Aplicando • ${market} • ${filterName}`);
 try{
  const q=new URLSearchParams({temporada:$('#season').value||'Todos',campeonato:'Todos',campeonatos:JSON.stringify(champPickerValues('#dashChampPicker')),mercado:market,pnl_ref:pnlRef,filtro_id:$('#dashFilter')?.value||'',comissao:localStorage.getItem('sofa_comissao')||'4.5'});
  const d=await api('/api/dashboard?'+q);
  renderDashboard(d);
  if(d.filter){setChampPicker('#dashChampPicker',d.filter.campeonatos||[],Boolean((d.filter.campeonatos||[]).length));}
  set('sideStatus','Conectado');
  set('configStatus',d.filter?.nome?`Banco B conectado • ${d.filter.nome} • ${d.marketLabel}`:`Banco B conectado • ${d.marketLabel}`);
 }catch(e){
  set('sideStatus','Erro');
  set('configStatus','Erro: '+e.message);
  throw e;
 }finally{
  if(btn){btn.disabled=false;btn.classList.remove('loading');btn.textContent='Aplicar';}
 }
}
async function options(){const d=await api('/api/dashboard?action=options');const fill=(id,vals)=>{const e=$(id);if(!e)return;e.innerHTML='<option>Todos</option>'+(vals||[]).map(x=>`<option>${esc(x)}</option>`).join('')};fill('#season',d.seasonsAvailable);fill('#btSeason',d.seasonsAvailable);fill('#btChamp',d.championshipsAvailable);renderChampPicker('#dashChampPicker',d.championshipsAvailable);renderChampPicker('#filterChampPicker',d.championshipsAvailable)}
function metricOptions(){return (metricData?.metricas||[]).filter(x=>x.ativa!==false&&x.ativo!==false).map(x=>`<option value="${x.id}" data-campo="${esc(x.campo||'')}">${esc(x.nome||x.name||('Métrica '+x.id))}</option>`).join('')}
const OFFICIAL_FIELDS=[
['RATING_CASA','Rating Casa'],['RATING_VISITANTE','Rating Visitante'],['GOLS_CASA_FT','Gols Casa FT'],['GOLS_VISITANTE_FT','Gols Visitante FT'],['XG_CASA','xG Casa'],['XG_VISITANTE','xG Visitante'],['XG_NO_ALVO_CASA','xG no alvo Casa'],['XG_NO_ALVO_VISITANTE','xG no alvo Visitante'],['FINALIZACOES_TOTAIS_CASA','Finalizações totais Casa'],['FINALIZACOES_TOTAIS_VISITANTE','Finalizações totais Visitante'],['FINALIZACOES_NO_ALVO_CASA','Finalizações no alvo Casa'],['FINALIZACOES_NO_ALVO_VISITANTE','Finalizações no alvo Visitante'],['FINALIZACOES_FORA_ALVO_CASA','Finalizações fora do alvo Casa'],['FINALIZACOES_FORA_ALVO_VISITANTE','Finalizações fora do alvo Visitante'],['FINALIZACOES_BLOQUEADAS_CASA','Finalizações bloqueadas Casa'],['FINALIZACOES_BLOQUEADAS_VISITANTE','Finalizações bloqueadas Visitante'],['ESCANTEIOS_CASA','Escanteios Casa'],['ESCANTEIOS_VISITANTE','Escanteios Visitante'],['POSSE_BOLA_CASA','Posse de bola Casa'],['POSSE_BOLA_VISITANTE','Posse de bola Visitante'],['PASSES_TOTAIS_CASA','Passes totais Casa'],['PASSES_TOTAIS_VISITANTE','Passes totais Visitante'],['PASSES_CERTOS_CASA','Passes certos Casa'],['PASSES_CERTOS_VISITANTE','Passes certos Visitante'],['PASSES_LONGOS_CERTOS_CASA','Passes longos certos Casa'],['PASSES_LONGOS_CERTOS_VISITANTE','Passes longos certos Visitante'],['CRUZAMENTOS_CERTOS_CASA','Cruzamentos certos Casa'],['CRUZAMENTOS_CERTOS_VISITANTE','Cruzamentos certos Visitante'],['TOQUES_AREA_ADVERSARIA_CASA','Toques na área adversária Casa'],['TOQUES_AREA_ADVERSARIA_VISITANTE','Toques na área adversária Visitante'],['ENTRADAS_TERCO_FINAL_CASA','Entradas no terço final Casa'],['ENTRADAS_TERCO_FINAL_VISITANTE','Entradas no terço final Visitante'],['DESARMES_TOTAIS_CASA','Desarmes totais Casa'],['DESARMES_TOTAIS_VISITANTE','Desarmes totais Visitante'],['PCT_DESARMES_GANHOS_CASA','% Desarmes ganhos Casa'],['PCT_DESARMES_GANHOS_VISITANTE','% Desarmes ganhos Visitante'],['INTERCEPTACOES_CASA','Interceptações Casa'],['INTERCEPTACOES_VISITANTE','Interceptações Visitante'],['RECUPERACOES_BOLA_CASA','Recuperações de bola Casa'],['RECUPERACOES_BOLA_VISITANTE','Recuperações de bola Visitante'],['CORTES_CLEARANCES_CASA','Cortes/Clearances Casa'],['CORTES_CLEARANCES_VISITANTE','Cortes/Clearances Visitante'],['PCT_DUELOS_GANHOS_CASA','% Duelos ganhos Casa'],['PCT_DUELOS_GANHOS_VISITANTE','% Duelos ganhos Visitante'],['DESARMES_SOFRIDOS_CASA','Desarmes sofridos Visitante'],['DESARMES_SOFRIDOS_VISITANTE','Desarmes sofridos Visitante']];
function fieldOptions(){const src=Array.isArray(metricData?.campose)&&metricData.campose.length?metricData.campose:OFFICIAL_FIELDS.map(([campo,nome])=>({campo,nome}));return src.map(x=>{const v=x.campo||x.field||x.nome||x.name||'';const label=x.nome||x.label||v;return v?`<option value="${esc(v)}">${esc(label)}${label!==v?' — '+esc(v):''}</option>`:''}).join('')}
async function loadMetrics(){const mf=$('#metricField');try{metricData=await api('/api/dashboard?action=metrics');set('metricMsg','');}catch(err){metricData={metricas:[],campose:OFFICIAL_FIELDS.map(([campo,nome])=>({campo,nome}))};set('metricMsg','API de métricas indisponível; campos oficiais carregados localmente.');}const ms=metricData.metricas||[];set('metricCount',ms.length+' métricas/configurações');if($('#metricBody'))$('#metricBody').innerHTML=ms.map(x=>{const active=x.ativa??x.ativo??true;const canManage=x.fonte==='metricas_config'||x.campo!==undefined;return `<tr><td>${x.id??''}</td><td>${esc(x.nome||x.name||'')}</td><td>${esc(x.campo||x.field||'')}</td><td>${esc(x.contexto||'')}</td><td>${x.janela_jogos??x.janela??''}</td><td>${x.minimo_jogos??x.minimo??''}</td><td>${esc(x.operacao||'')}</td><td><b class="pill ${active?'green':'red'}">${active?'Ativa':'Inativa'}</b></td><td>${canManage?`<button class="secondary metricEdit" data-id="${x.id}">Editar</button> <button class="secondary metricToggle" data-id="${x.id}" data-active="${active}">${active?'Desativar':'Ativar'}</button>${x.fonte==='metricas_config'?` <button class="remove metricDelete" data-id="${x.id}">Excluir</button>`:''}`:'—'}</td></tr>`}).join('')||emptyRow(9,'Nenhuma métrica cadastrada. Crie a primeira acima.');if(mf)mf.innerHTML='<option value="">Selecione um campo</option>'+fieldOptions()+`<option value="CUSTO_PONTO">CUSTO_PONTO — Custo do Ponto</option>`;$$('.metricSelect').forEach(e=>e.innerHTML='<option value="">Selecione uma métrica</option>'+metricOptions());}
async function editMetric(id){const x=(metricData?.metricas||[]).find(m=>String(m.id)===String(id));if(!x||x.fonte!=='metricas_config'){set('metricMsg','Esta métrica não pode ser editada.');return;}window.metricEditingId=Number(id);$('#metricName').value=x.nome||'';$('#metricDescription').value=x.descricao||'';const tipo=(x.formula?.tipo||((x.campo||'')==='COMPOSTA'?'COMPOSTA':(x.campo||'')==='CUSTO_PONTO'?'CUSTO_PONTO':'NORMAL')).toUpperCase();$('#metricType').value=tipo;if(tipo==='COMPOSTA'){syncMetricBuilder();$('#metricCompositeOperation').value=x.formula?.operacao||x.operacao||'MEDIA';const comps=x.formula?.componentes||[];$('#metricComponents').innerHTML='';comps.forEach(()=>addMetricComponent());$$('.compMetric').forEach((e,i)=>e.value=String(comps[i]?.metrica_id||''));}else{syncMetricBuilder();$('#metricField').value=x.campo||'';$('#metricContext').value=x.contexto||'CASA';$('#metricOperation').value=x.operacao||'MEDIA';$('#metricWindow').value=x.janela_jogos??x.janela??5;$('#metricMinimum').value=x.minimo_jogos??x.minimo??3;}const b=$('#saveMetric');if(b)b.textContent='Salvar alterações';set('metricMsg',`Editando métrica #${id}. Altere os campos e salve.`);document.querySelector('#page-metricas')?.scrollIntoView({behavior:'smooth',block:'start'});}
async function saveMetric(){const nome=$('#metricName').value.trim(),tipo=$('#metricType').value;if(!nome){set('metricMsg','Informe o nome da métrica.');return}let body={nome,descricao:$('#metricDescription').value.trim(),tipo};if(tipo==='COMPOSTA'){const comps=$$('.metricComponent').map(x=>({metrica_id:Number(x.querySelector('.compMetric').value)})).filter(x=>x.metrica_id>0);const op=$('#metricCompositeOperation')?.value||'MEDIA';if(comps.length<2){set('metricMsg','Adicione pelo menos 2 métricas à composição.');return}if(new Set(comps.map(x=>x.metrica_id)).size!==comps.length){set('metricMsg','Não repita a mesma métrica na composição.');return}body.campo='COMPOSTA';body.contexto='GERAL';body.janela_jogos=1;body.minimo_jogos=1;body.operacao=op;body.componentes=comps;}else{let campo=$('#metricField').value;if(tipo==='CUSTO_PONTO')campo='CUSTO_PONTO';if(!campo){set('metricMsg','Selecione um campo.');return}body.campo=campo;body.contexto=$('#metricContext').value;body.janela_jogos=Number($('#metricWindow').value||5);body.minimo_jogos=Number($('#metricMinimum').value||3);body.operacao=$('#metricOperation').value;}const payload=encodeURIComponent(JSON.stringify(body));set('metricMsg',window.metricEditingId?'Salvando alterações...':'Salvando...');const action=window.metricEditingId?`update_metric&id=${window.metricEditingId}&payload=${payload}`:`save_metric&payload=${payload}`;await api('/api/dashboard?action='+action);set('metricMsg',window.metricEditingId?'✓ Métrica atualizada no Banco B.':'✓ Métrica salva no Banco B.');window.metricEditingId=null;await loadMetrics();$$('.metricSelect').forEach(e=>e.innerHTML='<option value="">Selecione uma métrica</option>'+metricOptions());clearMetric(true);}
function addMetricComponent(){const w=$('#metricComponents');if(!w)return;const n=document.createElement('div');n.className='metricComponent';n.innerHTML='<label>Métrica<select class="compMetric"><option value="">Selecione uma métrica</option></select></label><button type="button" class="remove">Remover</button>';n.querySelector('.remove').onclick=()=>{n.remove()};w.appendChild(n);n.querySelector('.compMetric').innerHTML='<option value="">Selecione uma métrica</option>'+metricOptions();}
function syncMetricBuilder(){const t=$('#metricType'),normal=$('.metricNormalFields'),comp=$('#metricCompositeFields');if(!t)return;const isComp=t.value==='COMPOSTA';if(normal)normal.style.display=isComp?'none':'grid';if(comp)comp.style.display=isComp?'block':'none';if(isComp&&!$('#metricComponents')?.children.length){addMetricComponent();addMetricComponent();}}
function bindMetricType(){const t=$('#metricType'),f=$('#metricField');if(!t||!f)return;const sync=()=>{const special=t.value==='CUSTO_PONTO';f.disabled=special;if(special)f.value='CUSTO_PONTO';else if(f.value==='CUSTO_PONTO')f.value='';syncMetricBuilder();};t.onchange=sync;sync()}
function clearMetric(silent=false){window.metricEditingId=null;['metricName','metricDescription'].forEach(id=>{const e=$('#'+id);if(e)e.value=''});if($('#metricField'))$('#metricField').value='';if($('#metricContext'))$('#metricContext').value='CASA';if($('#metricOperation'))$('#metricOperation').value='MEDIA';if($('#metricWindow'))$('#metricWindow').value=5;if($('#metricMinimum'))$('#metricMinimum').value=3;if($('#metricType'))$('#metricType').value='NORMAL';if($('#metricComponents'))$('#metricComponents').innerHTML='';if($('#metricCompositeFields'))$('#metricCompositeFields').style.display='none';const b=$('#saveMetric');if(b)b.textContent='Salvar métrica';if(!silent)set('metricMsg','')}
function addMetricComponent(){const w=$('#metricComponents');if(!w)return;const n=document.createElement('div');n.className='metricComponent';n.innerHTML='<label>Métrica<select class="compMetric"><option value="">Selecione uma métrica</option></select></label><button type="button" class="remove">Remover</button>';n.querySelector('.remove').onclick=()=>{n.remove()};w.appendChild(n);n.querySelector('.compMetric').innerHTML='<option value="">Selecione uma métrica</option>'+metricOptions();}
function syncMetricBuilder(){const t=$('#metricType'),normal=$('.metricNormalFields'),comp=$('#metricCompositeFields');if(!t)return;const isComp=t.value==='COMPOSTA';if(normal)normal.style.display=isComp?'none':'grid';if(comp)comp.style.display=isComp?'block':'none';if(isComp&&!$('#metricComponents')?.children.length){addMetricComponent();addMetricComponent();}}
function bindMetricType(){const t=$('#metricType'),f=$('#metricField');if(!t||!f)return;const sync=()=>{const special=t.value==='CUSTO_PONTO';f.disabled=special;if(special)f.value='CUSTO_PONTO';else if(f.value==='CUSTO_PONTO')f.value='';syncMetricBuilder();};t.onchange=sync;sync()}
function clearMetric(silent=false){['metricName','metricDescription'].forEach(id=>{const e=$('#'+id);if(e)e.value=''});if($('#metricField'))$('#metricField').value='';if($('#metricContext'))$('#metricContext').value='CASA';if($('#metricOperation'))$('#metricOperation').value='MEDIA';if($('#metricWindow'))$('#metricWindow').value=5;if($('#metricMinimum'))$('#metricMinimum').value=3;if($('#metricType'))$('#metricType').value='NORMAL';if($('#metricComponents'))$('#metricComponents').innerHTML='';if($('#metricCompositeFields'))$('#metricCompositeFields').style.display='none';if(!silent)set('metricMsg','')}
async function loadFilters(){filterData=await api('/api/dashboard?action=filters');const fs=filterData.filtros||[];if($('#savedFilters'))$('#savedFilters').innerHTML=fs.filter(f=>Number.isInteger(Number(f.id))&&Number(f.id)>0).slice(0,5).map(f=>`<div class="saved"><div><b>${esc(f.nome)}</b><br><small>ID ${f.id} • ${f.ativo?'Ativo':'Inativo'} • ${(f.condicoes||[]).length} condição(ões)</small></div><div class="savedBtns"><button class="secondary editFilter" data-id="${f.id}">Editar</button><button class="secondary toggleFilter" data-id="${f.id}">${f.ativo?'Desativar':'Ativar'}</button><button class="danger deleteFilter" data-id="${f.id}">Apagar</button></div></div>`).join('')||'<span class="muted">Nenhum filtro salvo ainda.</span>';const active=fs.filter(f=>f.ativo&&Number.isInteger(Number(f.id))&&Number(f.id)>0);if($('#btFilter'))$('#btFilter').innerHTML='<option value="">Sem filtro</option>'+active.map(f=>`<option value="${f.id}">${esc(f.nome)}</option>`).join('');if($('#dashFilter')){const current=$('#dashFilter').value;$('#dashFilter').innerHTML='<option value="">Sem filtro</option>'+active.map(f=>`<option value="${f.id}">${esc(f.nome)}</option>`).join('');if(active.some(f=>String(f.id)===String(current)))$('#dashFilter').value=current;const chosen=active.find(f=>String(f.id)===String(current));if(chosen)setChampPicker('#dashChampPicker',chosen.campeonatos||[],Boolean((chosen.campeonatos||[]).length));}}
function addCondition(){const wrap=$('#conditions');if(!wrap)return;const n=document.createElement('div');n.className='condition';n.innerHTML=`<label>Métrica<select class="metricSelect"><option value="">Selecione uma métrica</option></select></label><label>Operador<select class="op"><option>></option><option>>=</option><option><</option><option><=</option><option>=</option><option><></option></select></label><label>Comparar com<select class="compareMode"><option value="VALOR">Valor</option><option value="METRICA">Outra métrica</option></select></label><label class="valueWrap">Valor<input class="val" type="number" step="0.01" value="2"></label><label class="compareWrap" style="display:none">Métrica comparada<select class="compareMetric"><option value="">Selecione uma métrica</option></select></label><label>Contexto<select class="ctx"><option>CASA</option><option>FORA</option><option>GERAL</option></select></label><label>Janela<input class="win" type="number" min="1" value="5"></label><label>Mínimo<input class="min" type="number" min="1" value="3"></label><label>Operação<select class="operation"><option>MEDIA</option><option>VALOR</option><option>SOMA</option><option>MIN</option><option>MAX</option><option>DESVIO_PADRAO</option><option>CV</option></select></label><button class="remove">Remover</button>`;n.querySelector('.remove').onclick=()=>{n.remove();updateConditionState()};const mode=n.querySelector('.compareMode');mode.onchange=()=>{const m=mode.value==='METRICA';n.querySelector('.valueWrap').style.display=m?'none':'block';n.querySelector('.compareWrap').style.display=m?'block':'none';};wrap.appendChild(n);if(metricData){n.querySelector('.metricSelect').innerHTML='<option value="">Selecione uma métrica</option>'+metricOptions();n.querySelector('.compareMetric').innerHTML='<option value="">Selecione uma métrica</option>'+metricOptions();}updateConditionState()}

function updateConditionState(){const cs=$$('.condition');cs.forEach((c,i)=>{const r=c.querySelector('.remove');if(r)r.disabled=cs.length===1;r.title=cs.length===1?'O filtro precisa ter pelo menos uma condição':'Remover condição';});}
async function editFilter(id){
 const d=await api('/api/dashboard?action=filter_detail&id='+Number(id)); const f=d.filtro;
 if(!f){set('filterMsg','Filtro não encontrado.');return;}
 if(!metricData)await loadMetrics(); editingFilterId=Number(id); $('#filterName').value=f.nome||'';
 const group=(d.nos||[]).find(n=>n.tipo==='GRUPO'); $('#filterLogic').value=group?.operador_logico||d.relacoes?.[0]?.operador||'E';
 setChampPicker('#filterChampPicker',f.campeonatos||[]);
 const wrap=$('#conditions');wrap.innerHTML='';
 const nodes=(d.nos||[]).filter(n=>n.tipo==='CONDICAO').sort((a,b)=>Number(a.ordem||0)-Number(b.ordem||0));
 nodes.forEach(n=>{const c=(d.condicoes||[]).find(x=>Number(x.no_id)===Number(n.id))||n;addCondition();const el=$('#conditions .condition:last-child');el.querySelector('.metricSelect').value=String(c.metrica_id||n.metrica_id||'');el.querySelector('.op').value=c.operador||n.comparador||'>';const cmp=c.metrica_comparada_id||n.metrica_comparada_id;el.querySelector('.compareMode').value=cmp?'METRICA':'VALOR';el.querySelector('.valueWrap').style.display=cmp?'none':'block';el.querySelector('.compareWrap').style.display=cmp?'block':'none';el.querySelector('.val').value=c.valor??n.valor??2;el.querySelector('.compareMetric').value=cmp?String(cmp):'';el.querySelector('.ctx').value=c.contexto||n.contexto||'CASA';el.querySelector('.win').value=c.janela??n.janela??5;el.querySelector('.min').value=c.minimo??n.minimo??3;el.querySelector('.operation').value=c.operacao||n.operacao||'MEDIA';});
 if(!nodes.length)addCondition(); const b=$('#saveFilter');if(b)b.textContent='Salvar alterações';set('filterMsg',`Editando filtro #${id}. Altere as condições e salve.`);document.querySelector('#page-filtros')?.scrollIntoView({behavior:'smooth',block:'start'});
}
async function saveFilter(){
 const nome=$('#filterName').value.trim()||'Novo filtro';
 const cond=$$('.condition').map(x=>{
   const s=x.querySelector('.metricSelect');const id=Number(s.value);const m=(metricData?.metricas||[]).find(z=>String(z.id)===String(id));
   const compare=x.querySelector('.compareMode')?.value||'VALOR';
   const out={metrica_id:id,campo:m?.campo||'',operador:x.querySelector('.op').value,valor:compare==='VALOR'?Number(x.querySelector('.val').value):null,percentual:null,metrica_comparada_id:compare==='METRICA'?Number(x.querySelector('.compareMetric').value)||null:null,contexto:x.querySelector('.ctx').value,janela:Number(x.querySelector('.win').value),minimo:Number(x.querySelector('.min').value||3),operacao:x.querySelector('.operation').value};
   return out;
 });
 if(cond.some(c=>!c.metrica_id)){set('filterMsg','Selecione uma métrica em todas as condições.');return}
 if(cond.some(c=>c.metrica_comparada_id===null && !Number.isFinite(c.valor))){set('filterMsg','Preencha o valor ou selecione uma métrica de comparação em todas as condições.');return}
 if(cond.some(c=>c.metrica_comparada_id!==null && (!Number.isInteger(c.metrica_comparada_id)||c.metrica_comparada_id<=0))){set('filterMsg','Selecione a métrica comparada em todas as condições.');return}
 set('filterMsg','Salvando filtro...');
 const payload=encodeURIComponent(JSON.stringify({nome,operador:$('#filterLogic').value,campeonatos:champPickerValues('#filterChampPicker'),condicoes:cond}));
 const action=editingFilterId?`update_filter&id=${editingFilterId}&payload=${payload}`:`save_filter&payload=${payload}`;
 await api('/api/dashboard?action='+action);set('filterMsg',editingFilterId?'✓ Filtro atualizado no Banco B.':'✓ Filtro salvo no Banco B.');editingFilterId=null;await loadFilters();$('#conditions').innerHTML='';addCondition();const fb=$('#saveFilter');if(fb)fb.textContent='Salvar filtro';
}
async function backtest(){const payload=encodeURIComponent(JSON.stringify({nome:$('#btName').value.trim()||'Meu Backtest',filtro_id:($('#btFilter').value && Number.isInteger(Number($('#btFilter').value)) && Number($('#btFilter').value)>0)?Number($('#btFilter').value):null,mercado:$('#btMarket').value,stake_fixa:Number($('#btStake').value||1),odd_minima:$('#btOddMin').value?Number($('#btOddMin').value):null,odd_maxima:$('#btOddMax').value?Number($('#btOddMax').value):null,temporada:$('#btSeason').value==='Todos'?null:$('#btSeason').value,campeonato:$('#btChamp').value==='Todos'?null:$('#btChamp').value}));set('btMsg','Salvando configuração e executando...');const d=await api('/api/dashboard?action=save_backtest_config&payload='+payload);const cfgId=Number(d?.config?.id);if(!Number.isInteger(cfgId)||cfgId<=0)throw Error('A configuração foi salva, mas o ID retornado é inválido.');const b=await api('/api/dashboard?action=backtest&config_id='+cfgId);set('btEntries',b.entries);set('btWin',fmt(b.winrate,1)+'%');set('btProfit',money(b.lucro));set('btROI',fmt(b.roi,1)+'%');set('btDD','-'+fmt(Math.abs(b.drawdown)));$('#btRows').innerHTML=(b.rows||[]).map(x=>`<tr><td>${esc(x.DATA)}</td><td>${esc(x.CONFRONTO)}</td><td>${esc(x.CAMPEONATO)}</td><td>${fmt(x.odd)}</td><td><b class="pill ${x.green?'green':'red'}">${x.green?'Green':'Red'}</b></td><td class="${x.pnl>=0?'positive':'negative'}">${money(x.pnl)}</td></tr>`).join('')||emptyRow(6,'Nenhuma entrada passou pelo recorte.');set('btMsg',`✓ Backtest executado${b.config?.filtro_id?' com filtro aplicado.':' sem filtro.'}`);await loadBacktestConfigs()}
async function loadBacktestConfigs(){try{const d=await api('/api/dashboard?action=backtest_configs'),xs=d.configs||[];set('btConfigCount',Math.min(5,xs.length||0)+' recentes');if($('#btConfigList'))$('#btConfigList').innerHTML=xs.filter(x=>Number.isInteger(Number(x.id))&&Number(x.id)>0).slice(0,5).map(x=>`<div class="saved"><div><b>${esc(x.nome||'Backtest '+x.id)}</b><br><small>ID ${x.id} • ${esc(x.mercado||'')} • Stake ${fmt(x.stake_fixa||1)}${x.filtro_id?' • Filtro #'+x.filtro_id:''}</small></div><button class="danger deleteBacktest" data-id="${x.id}">Apagar</button></div>`).join('')||'<span class="muted">Nenhuma configuração válida salva.</span>'}catch(e){set('btConfigCount','Erro ao carregar') }}
async function loadImportCount(){try{const d=await api('/api/dashboard?action=db_count');set('dbGameCount',Number(d.count||0).toLocaleString('pt-BR'));}catch(e){set('dbGameCount','—');}}
function normalizeImportHeader(h){return String(h??'').replace(/\ufeff/g,'').trim().toLocaleLowerCase('pt-BR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[()\-\/]/g,' ').replace(/\s+/g,' ').trim()}
async function parseImportFile(file){
 const name=String(file?.name||'').toLowerCase();
 if(!file)throw Error('Nenhum arquivo selecionado.');
 if(typeof XLSX==='undefined')throw Error('Leitor de planilhas não carregado. Recarregue a página e tente novamente.');
 const buf=await file.arrayBuffer();
 let wb;
 try{wb=XLSX.read(buf,{type:'array',cellDates:false,raw:false});}catch(e){throw Error('Não consegui ler este arquivo. Use XLSX, CSV, TSV ou TXT.');}
 const sheet=wb.Sheets[wb.SheetNames[0]];
 if(!sheet)throw Error('O arquivo não possui uma planilha válida.');
 const matrix=XLSX.utils.sheet_to_json(sheet,{header:1,defval:'',raw:false});
 const rows0=matrix.filter(r=>Array.isArray(r)&&r.some(v=>String(v??'').trim()!==''));
 if(!rows0.length)throw Error('O arquivo está vazio.');
 const headers=rows0[0].map(v=>String(v??'').trim());
 if(headers.length<2)throw Error('Não consegui identificar as colunas do arquivo.');
 const rows=[];
 for(let i=1;i<rows0.length;i++){const vals=rows0[i];if(!vals.some(v=>String(v??'').trim()!==''))continue;const r={};headers.forEach((h,j)=>r[h]=String(vals[j]??'').trim());rows.push(r)}
 return{headers,rows};
}
const IMPORT_ALIASES={
 'data':'DATA','date':'DATA','hora':'HORA','time':'HORA','confronto':'CONFRONTO','campeonato':'CAMPEONATO','competicao':'CAMPEONATO','temporada':'TEMPORADA',
 'gols casa ht':'GOLS_CASA_HT','gols visitante ht':'GOLS_VISITANTE_HT','gols casa ft':'GOLS_CASA_FT','gols visitante ft':'GOLS_VISITANTE_FT',
 'odds casa':'ODD_1X2_CASA','odd casa':'ODD_1X2_CASA','odds empate':'ODD_1X2_EMPATE','odd empate':'ODD_1X2_EMPATE','odds visitante':'ODD_1X2_VISITANTE','odd visitante':'ODD_1X2_VISITANTE',
 'over ht':'ODD_OVER_HT','over 0 5':'ODD_OVER_0_5','under 0 5':'ODD_UNDER_0_5','over 1 5':'ODD_OVER_1_5','under 1 5':'ODD_UNDER_1_5','over 2 5':'ODD_OVER_2_5','under 2 5':'ODD_UNDER_2_5','over 3 5':'ODD_OVER_3_5','under 3 5':'ODD_UNDER_3_5',
 'btts sim':'ODD_BTTS_SIM','btts nao':'ODD_BTTS_NAO','btts sim ft':'ODD_BTTS_SIM','btts nao ft':'ODD_BTTS_NAO',
 'lg score casa':'LG_SCORE_CASA','lg score visitante':'LG_SCORE_VISITANTE','hscore':'HSCORE','lg score':'LG_SCORE',
 'odd justa over 0 5':'ODD_JUSTA_OVER_0_5','odd justa under 0 5':'ODD_JUSTA_UNDER_0_5','odd justa over 1 5':'ODD_JUSTA_OVER_1_5','odd justa under 1 5':'ODD_JUSTA_UNDER_1_5','odd justa over 2 5':'ODD_JUSTA_OVER_2_5','odd justa under 2 5':'ODD_JUSTA_UNDER_2_5','odd justa over 3 5':'ODD_JUSTA_OVER_3_5','odd justa under 3 5':'ODD_JUSTA_UNDER_3_5'
};
const IMPORT_KNOWN=new Set(['DATA','HORA','CONFRONTO','CAMPEONATO','TEMPORADA','GOLS_CASA_HT','GOLS_VISITANTE_HT','GOLS_CASA_FT','GOLS_VISITANTE_FT','ODD_1X2_CASA','ODD_1X2_EMPATE','ODD_1X2_VISITANTE','ODD_OVER_HT','ODD_OVER_0_5','ODD_UNDER_0_5','ODD_OVER_1_5','ODD_UNDER_1_5','ODD_OVER_2_5','ODD_UNDER_2_5','ODD_OVER_3_5','ODD_UNDER_3_5','ODD_BTTS_SIM','ODD_BTTS_NAO','LG_SCORE_CASA','LG_SCORE_VISITANTE','HSCORE','LG_SCORE']);
function importFieldName(h){const raw=String(h??'').trim();const n=normalizeImportHeader(raw);if(IMPORT_ALIASES[n])return IMPORT_ALIASES[n];const direct=raw.toUpperCase().replace(/\s+/g,'_');return IMPORT_KNOWN.has(direct)?direct:null}
function importValue(field,v){let x=String(v??'').trim();if(!x)return null;if(field==='DATA'){let m=x.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})/);if(m)return `${m[3]}-${String(m[2]).padStart(2,'0')}-${String(m[1]).padStart(2,'0')}`;m=x.match(/^(\d{4})[\/-](\d{1,2})[\/-](\d{1,2})/);if(m)return `${m[1]}-${String(m[2]).padStart(2,'0')}-${String(m[3]).padStart(2,'0')}`;return x}if(['HORA','CONFRONTO','CAMPEONATO'].includes(field))return x;const n=Number(x.replace(/\s/g,'').replace(',','.'));return Number.isFinite(n)?n:x}
function seasonLabel(v){const s=String(v??'');return ({'58766':'2024','72034':'2025','2026':'2026'}[s]||s)}
function inferImportSeason(fileName){const m=String(fileName||'').match(/(?:^|[^0-9])(2024|2025|2026)(?:[^0-9]|$)/);return m?({'2024':'58766','2025':'72034','2026':'2026'}[m[1]]||m[1]):null}
function prepareImportRows(parsed,fileName=''){const fields=parsed.headers.map(h=>({header:h,field:importFieldName(h)}));const rows=[];let errors=0;const inferredSeason=inferImportSeason(fileName);for(const source of parsed.rows){const out={};fields.forEach(({header,field})=>{if(field){const v=importValue(field,source[header]);if(v!==null)out[field]=v}});if(!out.TEMPORADA&&inferredSeason)out.TEMPORADA=inferredSeason;if(!out.DATA||!out.CONFRONTO||!out.CAMPEONATO){errors++;continue}delete out.id;rows.push(out)}return{rows,errors,fields}}
function setImportStatus(type,title,detail=''){const e=$('#importStatus');if(!e)return;e.className='importStatus '+type;e.innerHTML=`<span class="statusDot"></span><b>${esc(title)}</b>${detail?`<small>${esc(detail)}</small>`:''}`}
function importLog(msg,type=''){const box=$('#importLog');if(!box)return;const div=document.createElement('div');div.className='logLine '+type;div.textContent=msg;box.prepend(div)}
async function startImport(){const file=$('#importFile')?.files?.[0];if(!file)return;const btn=$('#startImport');btn.disabled=true;$('#clearImport').disabled=true;setImportStatus('working','Preparando importação...','Lendo o arquivo e conferindo o Banco B.');$('#importLog').innerHTML='';let parsed;try{parsed=await parseImportFile(file)}catch(e){setImportStatus('error','Erro na leitura',e.message);btn.disabled=false;$('#clearImport').disabled=false;return}const prep=prepareImportRows(parsed,file.name);set('importTotal',prep.rows.length);set('importInserted','0');set('importSkipped','0');set('importErrors',prep.errors);if(!prep.rows.length){setImportStatus('error','Nenhum jogo válido',`Linhas descartadas: ${prep.errors}`);btn.disabled=false;$('#clearImport').disabled=false;return}try{const preview=await api('/api/dashboard?action=inspect_import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rows:prep.rows})});const season=preview.season?seasonLabel(preview.season):'';const champ=preview.championship||'';setImportStatus('ready','Arquivo conferido',`${preview.newCount} novo(s) • ${preview.existingCount} já existente(s)`);importLog(`PRÉVIA: ${preview.total} jogo(s) • ${preview.newCount} novo(s) • ${preview.existingCount} já existente(s).`,'ok');if(champ||season)importLog(`Identificação: ${champ||'Campeonato não informado'}${season?` • Temporada ${season}`:''}.`,'ok');const msg=`Encontramos ${preview.total} jogos.

${preview.newCount} serão importados.
${preview.existingCount} já existem no Banco B e não serão duplicados.${season?`

Temporada: ${season}`:''}${champ?`
Campeonato: ${champ}`:''}

Deseja continuar?`;if(!confirm(msg)){setImportStatus('ready','Importação cancelada','Nenhum jogo foi alterado.');importLog('Importação cancelada pelo usuário.','error');btn.disabled=false;$('#clearImport').disabled=false;return}}catch(e){setImportStatus('error','Erro na conferência',e.message);importLog(`Prévia: erro — ${e.message}`,'error');btn.disabled=false;$('#clearImport').disabled=false;return}setImportStatus('working','Importando...','Os jogos estão sendo gravados permanentemente no Banco B.');const batchSize=100,totalBatches=Math.ceil(prep.rows.length/batchSize);let inserted=0,skipped=0,errors=prep.errors;for(let i=0;i<prep.rows.length;i+=batchSize){const batch=prep.rows.slice(i,i+batchSize);const batchNo=Math.floor(i/batchSize)+1;set('importProgressLabel',`Gravando lote ${batchNo} de ${totalBatches}...`);try{const d=await api('/api/dashboard?action=import_games',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rows:batch})});inserted+=Number(d.inserted||0);skipped+=Number(d.skipped||0);errors+=Number(d.errors||0);set('importInserted',inserted);set('importSkipped',skipped);set('importErrors',errors);const pct=Math.round((Math.min(i+batch.length,prep.rows.length)/prep.rows.length)*100);$('#importProgress').style.width=pct+'%';set('importProgressText',pct+'%');importLog(`Lote ${batchNo}/${totalBatches}: ${d.inserted||0} importado(s), ${d.skipped||0} já existente(s).`,'ok')}catch(e){errors++;set('importErrors',errors);setImportStatus('error','Importação interrompida',e.message);importLog(`Lote ${batchNo}: erro — ${e.message}`,'error');btn.disabled=false;$('#clearImport').disabled=false;return}}$('#importProgress').style.width='100%';set('importProgressText','100%');set('importProgressLabel','Importação finalizada');setImportStatus('done','Importação finalizada',`${inserted} jogo(s) novo(s) salvo(s) permanentemente no Banco B.`);importLog(`FINALIZADO: ${inserted} novo(s), ${skipped} já existente(s), ${errors} erro(s).`,'done');btn.disabled=false;$('#clearImport').disabled=false;try{await options();await loadFilters();await dash()}catch{}}
function resetImport(){const f=$('#importFile');if(f)f.value='';set('importFileName','');set('importTotal','0');set('importInserted','0');set('importSkipped','0');set('importErrors','0');set('importProgressText','0%');set('importProgressLabel','Pronto para importar');$('#importProgress').style.width='0%';$('#startImport').disabled=true;$('#importLog').innerHTML='<div class="muted">Aqui aparecerá o progresso da importação.</div>';setImportStatus('idle','Aguardando arquivo');}
async function loadDeleteSeasons(){const sel=$('#deleteSeason'),btn=$('#deleteSeasonBtn');if(!sel)return;try{const d=await api('/api/dashboard?action=options');const seasons=d.seasonsAvailable||[];sel.innerHTML='<option value="">Selecione uma temporada</option>'+seasons.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');if(btn)btn.disabled=!seasons.length;}catch(e){sel.innerHTML='<option value="">Erro ao carregar</option>';if(btn)btn.disabled=true;}}
async function deleteSeason(){const sel=$('#deleteSeason'),season=sel?.value;if(!season)return;const ok=confirm(`ATENÇÃO: apagar todos os jogos da temporada ${season}.\n\nEsta ação é permanente e não pode ser desfeita.\n\nDeseja continuar?`);if(!ok)return;const btn=$('#deleteSeasonBtn');if(btn)btn.disabled=true;set('deleteSeasonMsg',`Apagando os jogos da temporada ${season}...`);try{const d=await api('/api/dashboard?action=delete_season&season='+encodeURIComponent(season),{method:'POST'});set('deleteSeasonMsg',Number(d.deleted||0)>0?`✓ Temporada ${season} apagada: ${Number(d.deleted||0).toLocaleString('pt-BR')} jogo(s) removido(s).`:`Nenhum jogo foi removido da temporada ${season}.`);await loadImportCount();await options();await loadFilters();await dash();await loadDeleteSeasons();}catch(e){set('deleteSeasonMsg','Erro: '+e.message);if(btn)btn.disabled=false;}}
function bindImport(){const f=$('#importFile'),drop=$('#importDrop');if(!f||!drop)return;f.addEventListener('change',()=>{const file=f.files?.[0];if(file){set('importFileName',file.name);$('#startImport').disabled=false;setImportStatus('ready','Arquivo pronto',`${file.name} • ${(file.size/1024).toFixed(1)} KB`)}else resetImport()});['dragenter','dragover'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.remove('drag')}));drop.addEventListener('drop',e=>{const file=e.dataTransfer.files?.[0];if(!file)return;try{const dt=new DataTransfer();dt.items.add(file);f.files=dt.files;f.dispatchEvent(new Event('change'))}catch{setImportStatus('error','Não foi possível anexar o arquivo','Use o botão de seleção.')}});$('#startImport')?.addEventListener('click',()=>startImport().catch(e=>{setImportStatus('error','Erro na importação',e.message);$('#startImport').disabled=false;$('#clearImport').disabled=false}));$('#clearImport')?.addEventListener('click',resetImport);$('#deleteSeasonBtn')?.addEventListener('click',()=>deleteSeason().catch(e=>set('deleteSeasonMsg','Erro: '+e.message)))}
function navigate(page){const b=$(`.nav[data-page="${page}"]`);$$('.nav').forEach(x=>x.classList.remove('active'));b?.classList.add('active');$$('.page').forEach(x=>x.classList.remove('active'));$(`#page-${page}`)?.classList.add('active');set('mobilePage',b?.querySelector('span')?.textContent||page);if(page==='metricas'&&!metricData)loadMetrics().catch(e=>set('metricMsg','Erro: '+e.message));if(page==='filtros'){if(!metricData)loadMetrics().then(loadFilters).catch(e=>set('filterMsg','Erro: '+e.message));else if(!filterData)loadFilters().catch(e=>set('filterMsg','Erro: '+e.message));}if(page==='backtest')loadBacktestConfigs().catch(()=>{});if(page==='importacao')loadImportCount().catch(()=>{});}
document.addEventListener('click',async e=>{const ef=e.target.closest('.editFilter');if(ef){try{await editFilter(ef.dataset.id)}catch(err){set('filterMsg','Erro: '+err.message)}return}const toggle=e.target.closest('.toggleFilter');if(toggle){try{await api('/api/dashboard?action=toggle_filter&id='+toggle.dataset.id);await loadFilters();set('filterMsg','✓ Status do filtro atualizado.')}catch(err){set('filterMsg','Erro: '+err.message)}return}const delFilter=e.target.closest('.deleteFilter');if(delFilter){if(!confirm('Apagar este filtro e suas condições? Esta ação não pode ser desfeita.'))return;try{await api('/api/dashboard?action=delete_filter&id='+delFilter.dataset.id);await loadFilters();set('filterMsg','✓ Filtro apagado.')}catch(err){set('filterMsg','Erro: '+err.message)}return}const delBt=e.target.closest('.deleteBacktest');if(delBt){if(!confirm('Apagar esta configuração de backtest? Esta ação não pode ser desfeita.'))return;try{await api('/api/dashboard?action=delete_backtest_config&id='+delBt.dataset.id);await loadBacktestConfigs();set('btMsg','✓ Configuração apagada.')}catch(err){set('btMsg','Erro: '+err.message)}return}const me=e.target.closest('.metricEdit');if(me){try{await editMetric(me.dataset.id)}catch(err){set('metricMsg','Erro: '+err.message)}return}const mt=e.target.closest('.metricToggle');if(mt){try{await api('/api/dashboard?action=toggle_metric&id='+mt.dataset.id+'&active='+mt.dataset.active);await loadMetrics();set('metricMsg','✓ Status da métrica atualizado.')}catch(err){set('metricMsg','Erro: '+err.message)}return}const del=e.target.closest('.metricDelete');if(del){if(!confirm('Excluir esta métrica/configuração?'))return;try{await api('/api/dashboard?action=delete_metric&id='+del.dataset.id);await loadMetrics();set('metricMsg','✓ Métrica excluída.')}catch(err){set('metricMsg','Erro: '+err.message)}return}const nav=e.target.closest('.nav');if(nav)navigate(nav.dataset.page)});
document.addEventListener('DOMContentLoaded',async()=>{set('appVersion',APP_VERSION);try{await options();await loadFilters();await dash()}catch(e){set('sideStatus','Erro');set('configStatus','Erro: '+e.message)}const ci=$('#exchangeCommission');if(ci)ci.value=localStorage.getItem('sofa_comissao')||'4.5';$('#saveCommission')?.addEventListener('click',()=>{const v=Number(ci.value);if(!Number.isFinite(v)||v<0||v>100){set('commissionMsg','Informe uma comissão entre 0 e 100%.');return}localStorage.setItem('sofa_comissao',String(v));set('commissionMsg','✓ Comissão salva.');dash().catch(()=>{})});$('#recentPageSize')?.addEventListener('change',e=>{recentPageSize=Number(e.target.value||20);recentPage=1;renderRecent(dashboardData?.rows||[])});$('#apply')?.addEventListener('click',()=>dash().catch(()=>{}));$('#pnlRef')?.addEventListener('change',()=>dash().catch(()=>{}));$('#dashFilter')?.addEventListener('change',()=>{const f=(filterData?.filtros||[]).find(x=>String(x.id)===String($('#dashFilter').value));if(f)setChampPicker('#dashChampPicker',f.campeonatos||[],Boolean((f.campeonatos||[]).length));dash().catch(()=>{})});addCondition();$('#addCondition')?.addEventListener('click',addCondition);$('#saveFilter')?.addEventListener('click',()=>saveFilter().catch(e=>set('filterMsg','Erro: '+e.message)));$('#saveMetric')?.addEventListener('click',()=>saveMetric().catch(e=>set('metricMsg','Erro: '+e.message)));$('#addMetricComponent')?.addEventListener('click',addMetricComponent);$('#clearMetric')?.addEventListener('click',()=>clearMetric());bindMetricType();$('#createBT')?.addEventListener('click',()=>backtest().catch(e=>set('btMsg','Erro: '+e.message)));loadFilters().catch(()=>{});loadBacktestConfigs().catch(()=>{});bindImport();loadImportCount().catch(()=>{});loadDeleteSeasons().catch(()=>{});});
